### ISSUE TITLE
Timer restart counts down in steps of 2s

### ISSUE THREAD

**Issue by andela-mallan** [meharbhutta/react-native-circular-timer#7]
@meharbhutta I implemented the restart that you suggested in the previous issue (thanks for that) but in a slightly different way. Rather than have a button to restart the counter, I used the `onTimeElapsed` callback to restart it. 
However, on restart, the timer counts down in steps of 2s i.e. if my duration was set at 5 secs, on restart, it counts down as "5...3...1", if 6 secs were set "6...4...2".
Have you encountered this? Or do you know where this stems from?

Below is the component that implements the timer
```
const Timer = ({ time, onTimeElapsed }) => {
  _restartTimer = () => {
    if (this._timerRef) {
      this._timerRef.restart();
    }
  };

  return (
    <View>
      <CircularTimer
        ref={refs => (this._timerRef = refs)}
        seconds={time}
        showSecond={true}
        radius={50}
        borderWidth={5}
        borderBackgroundColor='#f7f7f7'
        textStyle={{ fontSize: 20 }}
        onTimeElapsed={() => {
          onTimeElapsed();
          this._restartTimer();
        }}
      />
    </View>
  );
}

export default Timer;
```

**Comment by meharbhutta** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.
Thank you!
